### ISSUE TITLE
[Bug] Pyenv Virtual Python Not Detected

### ISSUE THREAD

**Issue by AlTimofeyev** [kiddae/neovim-dots#1]
Hi there, wasn't sure how to contact you so I opened an issue ticket.

This is trivial but I just had a quick question:
I keep getting the following error 

<img width="892" alt="Screen Shot 2022-05-23 at 21 04 36" src="https://user-images.githubusercontent.com/44423587/169947090-d9f99d66-10c7-415f-a8d9-6402fb3c75ce.png">

and I'm not really sure why and was wondering if you might know the cause or why it isn't detecting my python?
If not, then no worries! Please feel free to close this issue :)

#### Just A Bit More Details (Just In Case It Helps In Some Way):
I use PyEnv to manage my python versions and the global version of pyenv python is always linked to default to the `python` and `python3` commands in my system (pyenv does that somehow). I DO have a python3 executable located in the `usr/bin` directory by default, but for some reason it doesn't detect it either. Normally, I would check the `host stderr in messages` first, like it mentions in the error message, but I don't know where that's located. Unfortunately :(

**Comment by kiddae** [comment]
Hi,
I think running `:checkhealth` will tell you where it went wrong. My guess is that you don't have `pynvim` installed on your python environment.

**Comment by AlTimofeyev** [comment]
OHMYGOSH THIS WORKED!!!! Thank you so much! I installed `pynvim` and the error message went away! I ran `:checkhealth` like you suggested and it showed that `python3_host_prog` wasn't available, but it recognized my python version after installing `pynvim` and everything works now! Again! Thank you!! You rock!!
